version: '3'

services:
  cdn:
    build:
      context: .
    environment:
      SECRET_KEY_BASE: "${SECRET_KEY_BASE:-6PGeC2jbiA+2ngkf+yIT5qGGULtxJEp3hV4ZffMeEQx4B3yd3OHjt52rmYzrH3ih}"
    ports:
      - 4000:4000
    # volumes:
    #   - ./data:/etc/elixir_roots:rw